### ISSUE TITLE
Compilation error on non-gnu compilers

### ISSUE THREAD

**Issue by siexp** [4rtzel/cmake-qml-plugin-example#2]
Compilation error when building with on windows with MSVC
error: D8021 : invalid numeric argument '/Wextra'

https://github.com/4rtzel/cmake-qml-plugin-example/blob/2618614aac7799398e691f2d1a4dc1bcff13c547/plugins/my/plugin/example/CMakeLists.txt#L38

wrapping with fixes
```
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
    target_compile_options(
        ${PROJECT_NAME}
        PRIVATE
            -Wall
            -Wextra
            -Wpedantic
    )
endif()
```

**Comment by verbs2016** [comment]
> Compilation error when building with on windows with MSVC
> error: D8021 : invalid numeric argument '/Wextra'
> 
> https://github.com/4rtzel/cmake-qml-plugin-example/blob/2618614aac7799398e691f2d1a4dc1bcff13c547/plugins/my/plugin/example/CMakeLists.txt#L38
> 
> wrapping with fixes
> 
> ```
> if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
>     target_compile_options(
>         ${PROJECT_NAME}
>         PRIVATE
>             -Wall
>             -Wextra
>             -Wpedantic
>     )
> endif()
> ```

Try to comment out the "target_compile_options" at the below location:

 https://github.com/4rtzel/cmake-qml-plugin-example/blob/2618614aac7799398e691f2d1a4dc1bcff13c547/plugins/my/plugin/example/CMakeLists.txt#L38

**Comment by 4rtzel** [comment]
I've updated the CMakeLists.txt file with the suggested changes https://github.com/4rtzel/cmake-qml-plugin-example/commit/3967c261c605b0bcdf64d79fd29e0225009602e3.
